name: lumigator

services:
  ray:
    image: rayproject/ray:2.30.0-py311${COMPUTE_TYPE}${RAY_ARCH_SUFFIX}
    # https://docs.ray.io/en/releases-2.30.0/cluster/cli.html#ray-start for more info about the command
    runtime: nvidia
    privileged: true
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

  backend:
    environment:
      - RAY_WORKER_GPUS
      - RAY_WORKER_GPUS_FRACTION
