# this file is only for overrides during CI. pants will primarily process
# from the normal `pants.toml` file.

[docker]
use_buildx = true
build_args = ["HOME", "REPOVERSION"]
env_vars = [
  "REPOVERSION=%(env.REPOVERSION)s",
  "DOCKER_BUILDKIT=1",
  "DOCKER_CONFIG=%(homedir)s/.docker"
]

tools = [
  "dirname",
  "readlink",
  "python3",
  "cut",
  "sed",
  "bash",
]

