[project]
name = "common"
version = "0.1.0"
description = "Common deps to develop"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.0.1",
]

[project.optional-dependencies]
docs = [
    "sphinx>=8.1.3",
]
