{{- include "lumigator.lumigator-default-secret" . -}}
{{- if or (.Values.mistralAPIKey) (.Values.openaiAPIKey) -}}
{{- if .Values.existingSecret -}}
{{- fail "A key and an existing Secret name cannot be provided at the same time" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumigator.lumigator-secret-name" . }}
  labels:
    {{- include "lumigator.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.mistralAPIKey -}}
  {{ .Consts.mistralSecretKey }}: {{ .Values.mistralAPIKey | b64enc | quote }}
{{- end -}}
{{- if .Values.openaiAPIKey -}}
  {{ .Consts.openaiSecretKey }}: {{ .Values.openaiAPIKey | b64enc | quote }}
{{- end -}}
{{- end -}}