python_test_utils(
    name = "test_utils",
    dependencies = [
        "model_builder/python/mzai/model_builder/backend:model_builder",
        "model_builder/python/mzai/model_builder/backend/tests/fakes:fakes",
    ],
)
