apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-gpu
  region: us-east-2

iam:
  withOIDC: true

managedNodeGroups:
  - name: gpu-group
    amiFamily: Bottlerocket
    #ami: ami-custom1234
    instanceType: g5.xlarge

accessConfig:
  #authenticationMode: API_AND_CONFIG_MAP
  accessEntries:
    - principalARN: arn:aws:iam::381492205691:user/kyle
      accessPolicies:
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
