# Default values for lumigator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  s3Bucket: ""
  AWSAccessKey: ""
  AWSSecretKey: ""
  s3EndpointURL: ""
  AWSEndpointURL: ""

  # Name of the Ray head service
  rayAddress: lumigator-kuberay-head-svc
  rayPort: "8265"
  rayWorkerGPUs: "1.0"

  # Note: Need to manually delete PVC after helm delete
  postgresql:
    primary:
      initContainers:
        - command:
            - sh
            - -c
            - |
              uid
              mkdir -p $VOLUME_DATA_DIR
              chown -R 1001:1001 $VOLUME_DATA_DIR
              echo 'Volume permissions OK ✓'
          env:
            - name: VOLUME_DATA_DIR
              value: /bitnami/postgresql
          image: busybox
          imagePullPolicy: IfNotPresent
          name: volumepermissions
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: data

  kuberay-apiserver:
    image:
      repository: quay.io/kuberay/apiserver
      tag: 2.30.0
    security: {}

  ray-cluster:
    image:
      tag: 2.30.0-py311-gpu
    head:
      resources:
        limits:
          cpu: "8"
          memory: "20G" # 2GB is too low for object storage limits
          nvidia.com/gpu: "1"
        requests:
          # For production use-cases, we recommend specifying integer CPU requests and limits.
          # We also recommend setting requests equal to limits for both CPU and memory.
          # For this example, we use a 500m CPU request to accomodate resource-constrained local
          # Kubernetes testing environments such as KinD and minikube.
          cpu: "8"
          memory: "20G"
      env:
        - name: FSSPEC_S3_KEY
          value: ""
        - name: FSSPEC_S3_SECRET
          value: ""
        - name: FSSPEC_S3_ENDPOINT_URL
          value: ""
    worker:
      disabled: true
