# Default values for the lumigator backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

s3Bucket: ""
AWSAccessKey: ""
AWSSecretKey: ""
s3EndpointURL: ""
AWSEndpointURL: ""

rayAddress: ""
rayPort: "5432"
rayWorkerGPUs: ""

serviceAccountName: ""

existingMistralAPISecret: ""
mistralAPIKey: ""

evaluatorPipReqs: "/mzai/lumigator/python/mzai/jobs/evaluator/requirements.txt"
evaluatorWorkDir: "/mzai/lumigator/python/mzai/jobs/evaluator"

image:
  repository: "mzdotai/lumigator"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000
  annotations: {}

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Note: Need to manually delete PVC after helm delete
postgresql:
  enabled: true
  #  auth:
  #    username: lumigator
  #    database: lumigator
