name: mzai-platform
version: "3.8"


services:
  postgres:
#     platforms are specified for each for local dev. see
#     https://stackoverflow.com/questions/77023925/specify-platform-for-docker-image-in-visual-studio-code-devcontainers
    
    platform: linux/amd64
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ..:/workspace:cached
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=platform

  localstack:
    platform: linux/amd64
    image: localstack/localstack:3.4.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3:4566
      - CREATE_BUCKETS=platform-storage
    volumes:
      # Sync localstack startup scripts
      # https://docs.localstack.cloud/references/init-hooks/
      - ./localstack:/etc/localstack/init/ready.d
      # we mount the root of our codebase ('..') here
      - ..:/workspace:cached

  ray:
    platform: linux/amd64
    volumes:
      # we mount the root of our codebase ('..') here
      - ..:/workspace:cached
    image: mzdotai/platform:ray_jobrunner_dev

#    build:
#      context: ..
#      dockerfile: ".devcontainer/jobrunner.Dockerfile"
    command: bash -c "ray start --head --dashboard-host=0.0.0.0 --dashboard-port=8265 --block"
    ports:
      - 8265:8265
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=80

  backend:
    platform: linux/amd64
    volumes:
      # we mount the root of our codebase ('..') here
      - ..:/workspace:cached

    # has to be built first
    image: mzdotai/platform:backend_dev

    depends_on:
      - postgres
      - localstack
      - ray
    ports:
      - 80:80
    environment:
      - DEPLOYMENT_TYPE=local
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=platform
      - RAY_HEAD_NODE_HOST=ray
      - RAY_DASHBOARD_PORT=8265
      - AWS_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
      - S3_PORT=4566
      - S3_BUCKET=platform-storage


# for the devcontainer to work, this is the rough pattern i found that seemed worthwhile.
# docker compose needs a new 'service', defined here, that will explicitly be the dev container.
  # it has to run long enough to be pinged, hence the sleep command
  devenv:
    # this is the one built from source right now.
    #image: mzdotai/golden:base_latest

    build:
      context: ..
      dockerfile: ".devcontainer/devenv.Dockerfile"

    volumes:
      # we mount the root of our codebase ('..') here
      - ..:/workspace:cached
    # specify the platform; it'll be emulated locally via rosetta
    platform: linux/amd64
    # this is going to change

    command: echo $PATH


volumes:
    postgres-data:
