[project]
name = "3rdparty-python-dependencies"
version = "0.0.1"
requires-python = ">3.10,<=3.11"

dependencies = [
    "uvicorn[standard]==0.28.0",
    "fastapi[all]==0.110.0",
    "pydantic==2.6.4",
    "pydantic-settings==2.2.1",
    "click==8.1.7",
    "loguru==0.7.2",
    "pex==2.3.0",
    "httpx==0.27.0",
    "python-multipart==0.0.9",
    "pre-commit>=3.6",
    "sqlalchemy[asyncio]==2.0.28",
    "psycopg2-binary==2.9.9",
    "ray[default]==2.9.3",
    "boto3==1.34.105",
    "boto3-stubs[essential]==1.34.105",
    "starlette",
    "requests",
    "ruff",
    "pytest",
    "pytest-cov",
    "testcontainers",
    "setuptools==69.5.1",
    "numpy<2.0.0",
    "transformers==4.41.2",
    "s3fs==2024.5.0",
    "datasets==2.20.0"
]
