FROM python:3.10.13-bookworm

WORKDIR /mzai

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/mzai"

COPY platform/python/mzai .

ENTRYPOINT ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "80"]

