name: Check for Broken Links in Markdown

on:
    workflow_dispatch:
    push:
        branches:
            - '*'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Thanks https://github.com/marketplace/actions/lychee-broken-link-checker!
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
            # regex to exclude mailing addresses and localhost
            args: --base . --verbose --no-progress './**/*.md' --exclude 'mailto:|localhost'