name: Link checker

on:
  push:
    branches:
        - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  link-checker:
    name: Docs - Check for broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for modified paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes:
              - 'docs/**'

      - name: Link Checker
        if: steps.filter.outputs.changes == 'true'
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Documentation: https://github.com/lycheeverse/lychee?tab=readme-ov-file#commandline-parameters
          args: --base . --verbose --no-progress './**/*.md'  './**/*.rst' --exclude 'mailto:|localhost'
