name: Build and Publish Docs

on:
  # required to enable manual triggers on the GH web ui
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - "**"
  # separate workflow that runs on PRs to main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Set up Environment
      id: setup
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
      continue-on-error: false

    - name: Install Docs Dependencies
      id: install_build_dependencies
      run: |
        . .venv/bin/activate
        uv pip install -r pyproject.toml --extra docs
      continue-on-error: false

    - name: Build Documentation
      run: |
        . .venv/bin/activate
        cd docs
        sphinx-build source build/html

    - name: Set up Pages
      uses: actions/configure-pages@v4

    - name: Upload Artifact
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html/

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
