name: Lumigator pipeline

on:
  pull_request:
    branches:
      - "**"
    # synchronized is when you push new commits
    types: ["opened", "synchronize"]
  push:
    branches:
      - main
    tags:
      # Not the right semver regexp, but good enough
      - "v*.*.*"
  # required to enable manual triggers on the GH web ui
  workflow_dispatch:

jobs:
  helm:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
