name: Do not merge

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  do-not-merge:
    name: Prevent merge
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          if ${{ contains(github.event.pull_request.labels.*.name, 'do-not-merge') }}; then
            echo "PR is labeled with 'do-not-merge', merging disabled"
            exit 1
          fi
