name: SDK integration tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:


jobs:
  integration:
    name: SDK integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        run: uv python install
        working-directory: lumigator/python/mzai/sdk

      - name: Setup containers
        run: make start-lumigator

      - name: Run tests
        run: uv run pytest -o "python_files=int_test_*.py" tests
        working-directory: lumigator/python/mzai/sdk

      - name: Teardown containers
        run: make stop-lumigator
