name: Lumigator backend tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  backend-integration-tests:
    name: Backend integration tests - Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install
        working-directory: lumigator/python/mzai/backend

      - name: Lint
        run: uvx ruff check --config ruff.toml
        continue-on-error: false

      - name: Run backend unit tests
        run: make test-backend-unit

      - name: Run backend integration tests
        run: KEEP_CONTAINERS_UP=FALSE AUTO_TEST_RUN=y make test-backend-integration

      - name: Collect Ray logs in case of failure
        if: failure()
        run: |
          mkdir /tmp/raylogs
          docker cp lumigator-ray-1:/tmp/ray/ /tmp/raylogs/

      - name: Upload Ray logs in case of failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ray-logs
          path: /tmp/raylogs/ray/session_*/logs/
